### PR TITLE
Allie

### PR DESCRIPTION
**Pull request by achang209**

### CODE REVIEW

**Comment by achang209** [comment]
Ran Plan for dir: `staging` workspace: `staging`

<details><summary>Show Output</summary>

```diff
aws_instance.staging_example: Refreshing state... [id=i-0f9db7ff1a4196654]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_instance.staging_example will be updated in-place
~ resource "aws_instance" "staging_example" {
        id                                   = "i-0f9db7ff1a4196654"
      ~ instance_type                        = "t2.small" -> "t2.medium"
        tags                                 = {
            "Name" = "staging-example"
        }
        # (38 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
</details>

* :arrow_forward: To **apply** this plan, comment:
  ```shell
  atlantis apply -d staging -w staging
  ```
* :put_litter_in_its_place: To **delete** this plan and lock, click [here](https://fd74-2600-6c40-59f0-b8b0-4474-a87c-c911-5975.ngrok-free.app/lock?id=achang209%252Fterraform-atlantis%252Fstaging%252Fstaging)
* :repeat: To **plan** this project again, comment:
  ```shell
  atlantis plan -d staging -w staging
  ```
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this Pull Request, comment:
  ```shell
  atlantis apply
  ```
* :put_litter_in_its_place: To **delete** all plans and locks from this Pull Request, comment:
  ```shell
  atlantis unlock
  ```

**Review by achang209314 — APPROVED** [review]
lgtm

**Comment by achang209** [comment]
atlantis apply

**Comment by achang209** [comment]
Ran Apply for dir: `staging` workspace: `staging`

<details><summary>Show Output</summary>

```diff
aws_instance.staging_example: Modifying... [id=i-0f9db7ff1a4196654]
aws_instance.staging_example: Still modifying... [id=i-0f9db7ff1a4196654, 10s elapsed]
aws_instance.staging_example: Still modifying... [id=i-0f9db7ff1a4196654, 20s elapsed]
aws_instance.staging_example: Still modifying... [id=i-0f9db7ff1a4196654, 30s elapsed]
aws_instance.staging_example: Still modifying... [id=i-0f9db7ff1a4196654, 40s elapsed]
aws_instance.staging_example: Still modifying... [id=i-0f9db7ff1a4196654, 50s elapsed]
aws_instance.staging_example: Still modifying... [id=i-0f9db7ff1a4196654, 1m0s elapsed]
aws_instance.staging_example: Still modifying... [id=i-0f9db7ff1a4196654, 1m10s elapsed]
aws_instance.staging_example: Still modifying... [id=i-0f9db7ff1a4196654, 1m20s elapsed]
aws_instance.staging_example: Modifications complete after 1m23s [id=i-0f9db7ff1a4196654]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

</details>

**Comment by achang209** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `staging` workspace: `staging`

**Pull request merged**
